project:
  type: website
  preview:
    port: 4200
    browser: true
  render:
    - "*.qmd"
  output-dir: _site

website:
  page-navigation: true
  reader-mode: false
  back-to-top-navigation: true
  repo-url: https://github.com/elsdes3/devcontainer-notebooks
  repo-actions: [edit, issue]
  title: "Dev Container Multi-Step Notebooks Workflow"

  navbar:
    background: primary
    search: false

  page-footer:
    left: ""
    right: ""

format:
  html:
    grid:
      margin-width: 300px
      body-width: 1100px
      gutter-width: 1.5em
    smooth-scroll: true
    theme: materia
    code-copy: true
    code-overflow: wrap
    code-fold: false
    echo: false
    toc: true
    toc-expand: 3
    toc-title: On this page
    toc-location: right
    toc-fold: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'

filters:
  - quarto
