name: eda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip==23.2.1
  - pip:
    - Jinja2==3.1.2
    - boto3
    - s3fs>=2023.6.0
    - requests==2.31.0
    - altair==5.1.2
  - conda:
    - ipykernel==6.25.2
    - gcc==13.2.0
    - pyarrow==13.0.0
    - pandas==2.0.0
    - duckdb-engine==0.9.2
    - python-duckdb==0.9.0
    - ibis-framework[pandas]==7.0.0
    - ibis-framework[duckdb]==7.0.0
